### ISSUE TITLE
Mysterious span wrappers

### ISSUE THREAD

**Issue by lorefnon** [inferinc/bobtail#1]
Great work on the project. There seems to be a weird issue when using the templating system

When I try to follow along the example : 

<pre><code>
div {class: 'sidebar'}, [
  h2 {}, ['Send a message']
  form {action: '/msg', method: 'POST'}, [
    input {type: 'text', name: 'comment', placeholder: 'Your message'}, []
    select {name: 'recipient'}, [
      option {value: '0'}, ['John']
      option {value: '1'}, ['Jane']
    ]
    button {class: 'submit-btn'}, ['Send']
  ]
]
</code></pre>

The DOM I get is : 
![spans](https://f.cloud.github.com/assets/1449492/867988/e8e0fb6c-f760-11e2-86b9-8e2044b1dad8.png)

All the text nodes are wrapped inside `<span>` tags.

**Comment by yang** [comment]
@lorefnon Thanks for filing. Indeed, this is actually a known issue (the result of a quick hack to get things mostly working) and is called out in http://yang.github.io/reactive-coffee/infelicities.html#text-spans. It is somewhat low-hanging, and just needs to be done.

**Comment by lorefnon** [comment]
While I was looking into the [development setup](http://yang.github.io/reactive-coffee/dev-setup.html) I ran into a couple of issues - The tests seem to expect client side dependencies in components folder where as bower installs them in bower_components. This is likely to be a case of backward incompatibility with bower, though I am not sure - it may be worthwhile to mention the bower version required, or just make adjustments to use the latest version of bower.

**Comment by lorefnon** [comment]
This may be a plausible solution : http://pastie.org/8183372

**Comment by yang** [comment]
@lorefnon Thanks for the notes! I've updated bower usage and the website dev setup instructions as well. With regard to your fix, the ObsArray handling needs to be updated too - hoping to have some time to iron this out later today or tomorrow.

**Comment by lorefnon** [comment]
This is great. Thanks for being helpful and fixing the issue so quickly.

**Comment by yang** [comment]
@lorefnon Sure thing! Also a new version release (with the fix) is now out.
