### ISSUE TITLE
Element Cleanup

### ISSUE THREAD

**Issue by eizenberg** [inferinc/bobtail#10]
My elements often define intervals:

``` coffeescript
blinkingBox (opts) ->
   active =  rx.cell false
   flipActive = -> active.set not active.get()
   setInterval flipActive, opts.ms ? 500

   div { class: bind -> if active then 'red-box' else 'black-box' }
```

These intervals need to be cleaned up.
For example, an element might be removed from `boxes`:

``` coffeescript
$('body').attach [
   div { class: 'container' }, boxes.map ->
      blinkingBox()
]
```

I would imagine there should be some sort of cleanup callback:

``` coffeescript
blinkingBox (opts) ->
   // ...
   blink = setInterval flipActive, opts.ms ? 500
   $div = div { class: bind -> if active then 'red-box' else 'black-box' }
   $div.onDetach = -> cleanInterval blink
```

Not sure this is the best solution, but listening to `boxes.onRemove` sounds like a lot of boilerplate, for a common use case.

**Comment by yang** [comment]
Indeed—`boxes.onRemove` would furthermore break encapsulation of `blinkingBox` concerns. In the interest of not requiring resource cleanup to be tied to any specific DOM element, and instead associating it with the current `bind` context, I'll add a simple `rx.onDispose(callback)` function, which is probably the most straightforward solution for now.
