### ISSUE TITLE
lagBind

### ISSUE THREAD

**Issue by eizenberg** [inferinc/bobtail#12]
I think there are three issues with the existing lagBind implementation:
1. rx.lagBind shortcut doesn't activate 'lag' parameter of DepCell's constructor
2. 500ms lag is hardcoded (already documented)
3. You cannot dynamically define lag in the source cell

Right now I'm using an alternative lagBind directive:

``` coffeescript
lagBind = (init, fn) ->

    now = bind fn
    future = rx.cell init

    timeout = null

    now.onSet.sub rx.skipFirst ([o, n]) ->
        (clearTimeout timeout) if timeout?

        timeout = setTimeout ( ->
            timeout = null
            future.set n.val
        ), n.ms

    future
```

Here's how I use it:

``` coffeescript
showTooltip = lagBind false, ->
    if focused.get() and showTooltips.get() then val: true, ms: 0
    else val: false, ms: 300
```

The tootip appears instantly, but disappears only after a delay.

**Comment by yang** [comment]
Nice!

`lagBind` is definitely broken/neglected—sorry for that, fixing.  There's a subtle difference between the two `lagBind`s however—the original `lagBind` consists of a _pre-evaluation_ lag, and yours consists of a _post-evaluation_ lag.  The intent for pre-evaluation `lagBind` is to delay evaluation of certain expensive `bind`s, e.g.:

``` coffeescript
div {class: 'complex-stuff'}, lagBind [], ->
  renderComplexContents()
```

Your example also makes sense to me, though; there seems to be a place for both (and for dynamic post-evaluation lag).  I'm going ahead and putting this in (possibly refactoring out some more general asynchronous binding mechanism).

Thanks @eizenberg, keep these coming!
