### ISSUE TITLE
Auto cssify

### ISSUE THREAD

**Issue by eizenberg** [inferinc/bobtail#15]
I love rxt.cssify. It made my code much cleaner.
What do you think about running it automatically on the style attribute if its value is of type object?

This:

``` coffee-script
div {
   style: rxt.cssify
      color: 'red'
      backgroundColor: 'grey'
      fontSize: '24px'
}, 'Lorem Ipsum'
```

Becomes this:

``` coffee-script
div {
   style:
      color: 'red'
      backgroundColor: 'grey'
      fontSize: '24px'
}, 'Lorem Ipsum'
```

Alternatively, you can support a virtual attribute (e.g. calcStyle) and convert its value to a cssified style.

**Comment by yang** [comment]
Sounds good!  It makes sense as a built-in `specialAttr`.
