### ISSUE TITLE
Unable to include html fragments

### ISSUE THREAD

**Issue by michj** [inferinc/bobtail#16]
I have a section of code that spits out an HTML string that I need to include in the reactive.coffee markdown, but it does not seem to be working.

According to the documentation the content for a tag should accept a jQuery wrapped list of doc nodes. But I'm struggling to make this work.

Example code ... 

```
n1 = 'hello'
n2 = $('<h1>Hello</h1><p>Paragraph</p>')
```

Now

```
$('body').append(div {}, n1)
```

works, but

```
$('body').append(div {}, n2)
```

fails with an `Unknown type for contents`

What am I missing?

**Comment by eizenberg** [comment]
`$('body').append(div {}, [n2])` should work

**Comment by yang** [comment]
So, there are actually two things going on with what you're passing in.

First is that, as @eizenberg mentions, the wrapper expects elements to be wrapped in an array. We do accept also a single text string for the common use case of something like:

``` coffeescript
h1 'hello world'
```

The following is (debatably!) a bit less readable:

``` coffeescript
div div 'hello'
```

And hence we wanted to encourage array-wrapping:

``` coffeescript
div [div 'hello']
```

This also keeps the system simpler in that there are fewer type-based overloads.  These are all minor arguments however.  There's also something to be said for preserving symmetry between strings and elements.

The second thing going on is that you're passing in a jQuery wrapper around multiple top-level elements.  This is something that the library doesn't currently handle, for no good reason other than that most of the time you're just passing in `Array`s or `rx.array`s of rxt tags, like:

``` coffeescript
ul {...}, items.map (item) ->
  li {...}, item
```

If you later remove from or insert into `items`, the system has a slightly easier time knowing what to update in the DOM.

**Quick fix** for both the above is to just break it up into an array of multiple objects:

``` coffeescript
n2 = [$(x) for x in n2]
```

**Resolutions**: I'll tentatively push in some code for the following:
- more useful error messages :)
- error on jQuery objects of multiple elements
- accept jQuery objects as well as of arrays of jQuery objects
- accept raw elements as well as jQuery objects
- accept jQuery objects of multiple elements

Thanks!

**Comment by yang** [comment]
Closing this for now - I won't make the last change since it would inflate the core code complexity for relatively minor gain (trivial for users to conform to the current API).  May revisit once we have a better story for flattening `ObsArray`s.
