### ISSUE TITLE
jQuery plugin : propagation

### ISSUE THREAD

**Issue by Yakulu** [inferinc/bobtail#17]
Good morning,

I've just began to test and play with reactive.coffee (thanks for it).
I hope to haven't mistaken the usage, but I not, I suggest that when we use the jQuery plugin, setting a value applies it to the jQuery Element.

I tried to make a [little example](http://jsfiddle.net/KNfNH/1/) to make more sense.

**Comment by yang** [comment]
The jQ plugin is for convenience and allows you to react to the (user-driven) changes made to an input—hence those cells are read-only dependent cells (`DepCell`) and have no `set` method.

It's already pretty easy to set a value on the input box:

```
$myInput.val('foo')
```

Alternatively, if you want the contents/value of something to always be bound to a cell, you'd declare it as such:

```
mytext = rx.cell('foo')
input {type: 'text', value: bind -> mytext.get()}
mytext.set('bar')
```

Let me know if this makes sense, or if I'm misunderstanding / you have a use case for making this interface writable.  Thanks!

**Comment by Yakulu** [comment]
Your answer makes sense. Binding the value sounds like a proper way to do this.
Thank you for your reactivity (sorry about that play on words ;)) and this fine library.
Issue closed.
