### ISSUE TITLE
Examples could run easier out-of-the-box

### ISSUE THREAD

**Issue by deanrad** [inferinc/bobtail#29]
There are a few obstacles which I'm trying to address for getting examples up and running. 
- In "react-tut", new comments get erased, since no server-side code exists to update comments.json - I think the example is served better without polling
- script tags refer to ../dist version with bower versions commented out (see comments)

Regarding working locally without thrashing the script tag, have you seen `bower link` ? I think we can use the bower layer to work locally instead, so I deleted the links to ../dist

The rest I think are minor updates I needed to get examples looking better 'out-of-the-box'.

**Comment by yang** [comment]
Great observations. I should probably also actually mention somewhere that these examples even exist.

I had no idea about `bower link`, seems perfect for this use case.
