### ISSUE TITLE
Remove jQuery dependency

### ISSUE THREAD

**Issue by piranha** [inferinc/bobtail#3]
If that's not hard. I mean why depend on jQuery if you can skip that? I've looked at code, and there is only two places where it's used:

```
elt = $("<#{tag}/>") # line 345
```

This could be just `document.createElement(tag)`, with the additional benefit of being just faster. And another one is here:

```
      else if child instanceof RawHtml
        parsed = $(child.html)    # line 359
        throw 'Cannot insert RawHtml of multiple elements' if parsed.length
        parsed[0]
```

Here I'm not sure what's meant to happen, but if it's parsing string to DOM nodes, it could be done with a simple helper...

What do you think?

**Comment by yang** [comment]
It's also used in prop/attr manipulation, event handlers, etc. Basically it's used as the lower-level, cross-browser DOM manipulation layer. No strong dogmatism here though - definitely would be neat to see what things would look like without jQuery, and provide that as the core.
