### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by deanrad** [inferinc/bobtail#46]
Some key components have fallen behind (run `npm outdated`), particularly coffeescript could be updated to 1.7.x by updating grunt-contrib-coffee.. Also, is there any use for grunt-google-cdn ? 

Also, is yeoman in use still, or can yeoman-related variables be removed from the Gruntfile ? 

grunt-contrib-connect        0.2.0        0.2.0          0.7.1  grunt-contrib-connect
grunt-contrib-coffee         0.6.7        0.6.7         0.10.1  grunt-contrib-coffee
grunt-contrib-concat         0.1.3        0.1.3          0.4.0  grunt-contrib-concat
....

**Comment by yang** [comment]
I have no idea, but giving this a shot....
