### ISSUE TITLE
Include source maps in dist/ directory

### ISSUE THREAD

**Issue by deanrad** [inferinc/bobtail#52]
Should the build process include source maps in the dist/ directory ? I see components such as jQuery distribute their source maps, and I see reactive builds them.. I think it'd be helpful for stepping through the source. Also, the source .coffee file would need to resolve correctly relative to the sourcemap for a browser to pick it up.. Shouldn't be too much work, I think..

**Comment by yang** [comment]
Sounds perfectly sensible!  Do you know how to configure this?

**Comment by deanrad** [comment]
I think this sums it up: http://bit.ly/1zq1VyJ and I'll get a chance to try it later..
