### ISSUE TITLE
ES6 Object.observe?

### ISSUE THREAD

**Issue by deanrad** [inferinc/bobtail#54]
Is there any chance that reactive will benefit from the new stuff in Object.observe ?
http://addyosmani.com/blog/the-future-of-data-binding-is-object-observe/

**Comment by yang** [comment]
Why yes in fact that has been on the ideas list for some time! See
http://yang.github.io/reactive-coffee/ideas.html#object-observe

I think, however, that ES5 properties (support for which has also been in
the library for a while) already get us most of the way there.

**Comment by deanrad** [comment]
Thanks for the pointer.
