### ISSUE TITLE
Enhancement: Allow observable objects as alternative to 'cells'

### ISSUE THREAD

**Issue by m1sta** [inferinc/bobtail#6]
Using individual variables for elements in a reactive chain forces you to keep using .get() and .set(). Syntax would be cleaner if this could be avoided through the use of getter and setter functions on object properties. All variables linked to a template could be hosted within a single 'document' (ie. the graph of data used within a reactive view).

A simple function called 'reactive' which makes changes to any object observable could make for some very clean syntax like the following...

``` coffeescript
    reactive class task
       constructor: (description, priority, isDone) ->
           [@description, @priority, @isDone] = [description, priority, isDone]

    taskList = reactive array
       0: new task 'a','b','c'
       1: new task 'd','e','f'

```

I'm obviously using a simple helper function called 'array' because I've got unlove for brackets but it's just as nice when a standard array is being passed to the 'reactive' function.

**Comment by yang** [comment]
This makes a lot of sense. We'd love to add this into a release soon. Thanks!

**Comment by yang** [comment]
Digging into this now - the syntax will likely be a bit different, in that you need to define the property descriptors based on the values (post-constructor-time) or some field spec (at class definition time).
