### ISSUE TITLE
Problem with ObsMap::realPut

### ISSUE THREAD

**Issue by eizenberg** [inferinc/bobtail#7]
In ObsMap::realPut, I think it should be `if key of @x` not `if key in @x`.
Also, shouldn't the 'add' case also fire an onChange event?

```
  realPut: (key, val) ->
    if key in @x
      old = @x[key]
      @x[key] = val
      @onChange.pub([key, old, val])
      old
    else
      @x[key] = val
      @onAdd.pub([key, val])
      undefined
```

Should I make a pull request?

**Comment by yang** [comment]
Thanks! Certainly feel free to issue a pull request for the `of` typo. Actually for newly added entries, `onAdd` is the event that fires; `onChange` is for existing keys and `onRemove` is for deletions.

**Comment by eizenberg** [comment]
Hi, thanks for fixing the issue!

Regarding the onChange event for new keys:
You can see my use case here - http://jsfiddle.net/fcJxP/62/
Shouldn't ObsMap.get react to new keys the same way it reacts to existing ones?

**Comment by yang** [comment]
Ah, yeah - that's because .get() and .all() need to subscribe to not just onChange events.  (Sorry for the bumps - the ObsMap hierarchy as a whole hasn't really been tested.)

**Comment by eizenberg** [comment]
Thanks for fixing this one quickly.
I'm really enjoying working with reactive-coffee so far.
